### PR TITLE
Bug fix for deprecated Policies

### PR DESCRIPTION
**Pull request by apybar**

### CODE REVIEW

**Review by brianmooremsft — APPROVED** [review]
Approving based on scope of effect and breaking nature.

**Comment by arrerezai** [comment]
Bug is fixed with this solution indeed, however, the entire change from epac 10.3.4 to 10.4.0(1) makes the Plan stage way slower than before. Please see the following images:

v10.3.4:
image

v10.4.0 (with this bug fix):
image

**Comment by apybar** [comment]
@arrerezai - noted. Will continue to do testing and push updates this week.

**Comment by arrerezai** [comment]
@apybar - did you review this yet? Things are moving really really slow now since this update. Would be nice to have the speed back. Cheers.

**Comment by arrerezai** [comment]
@apybar @anwather I can also confirm the speed is back now and works like a charm - thanks gents!

**Pull request merged**
